name: Build and Test (macOS)
on:
  push:
    branches:
      - main
jobs:
  build-and-test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: gcc randchar.c -o randchar
      - run: ./randchar
      - run: ./randchar -length 100
      - run: ./randchar -no-special-characters
      - run: ./randchar -no-special-characters -length 100
