name: Build and Test (Windows)
on:
  push:
    branches:
      - main
jobs:
  build-and-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: gcc main.c -O2 -Wall -o randchar.exe
      - run: .\randchar.exe
      - run: .\randchar.exe -length 100
      - run: .\randchar.exe -no-special-characters
      - run: .\randchar.exe -no-special-characters -length 100
